# Generated by Django 5.1.7 on 2025-05-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_systemsettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Khi tắt, website sẽ hiển thị trang bảo trì cho người dùng thông thường'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Khi bật chế độ bảo trì, website sẽ hiển thị trang bảo trì cho người dùng thông thường'),
        ),
    ]
