# Generated by Django 5.1.7 on 2025-05-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_category_image'),
    ]

    operations = [
    ]
