# Generated by Django 5.1.7 on 2025-05-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(help_text='URL của hình ảnh sản phẩm trên Cloudinary', max_length=500),
        ),
    ]
