# Generated by Django 5.1.7 on 2025-05-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
