# Generated by Django 5.1.7 on 2025-05-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, help_text='URL của ảnh đại diện trên Cloudinary', max_length=500, null=True),
        ),
    ]
