# Generated by Django 5.0.1 on 2025-05-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_options_remove_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, default='SOME_DEFAULT_NUMBER', editable=False, help_text='Mã đơn hàng, sẽ được tạo tự động', max_length=50, null=True, unique=True),
        ),
    ]
