# Generated by Django 5.0.1 on 2025-05-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, editable=False, help_text='Mã đơn hàng, sẽ được tạo tự động', max_length=50, null=True, unique=True),
        ),
    ]
