# Generated by Django 5.0.1 on 2025-05-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('processing', 'Đang xử lý'), ('delivering', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
