# Generated by Django 5.0.1 on 2025-05-06 20:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_users_date_joined_alter_users_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='image_url',
        ),
        migrations.AddField(
            model_name='books',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Hình ảnh sản phẩm sách (tải lên Cloudinary)', max_length=255, null=True, verbose_name='image'),
        ),
    ]
